// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id, user_id, name, provider, region, endpoint,
    encrypted_access_key, encrypted_secret_key,
    use_ssl, status, logo
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, name, provider, region, endpoint, encrypted_access_key, encrypted_secret_key, use_ssl, status, logo, created_at, updated_at
`

type CreateCredentialParams struct {
	ID                 pgtype.UUID `json:"id"`
	UserID             pgtype.UUID `json:"user_id"`
	Name               string      `json:"name"`
	Provider           string      `json:"provider"`
	Region             string      `json:"region"`
	Endpoint           string      `json:"endpoint"`
	EncryptedAccessKey string      `json:"encrypted_access_key"`
	EncryptedSecretKey string      `json:"encrypted_secret_key"`
	UseSsl             bool        `json:"use_ssl"`
	Status             string      `json:"status"`
	Logo               *string     `json:"logo"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Provider,
		arg.Region,
		arg.Endpoint,
		arg.EncryptedAccessKey,
		arg.EncryptedSecretKey,
		arg.UseSsl,
		arg.Status,
		arg.Logo,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.Endpoint,
		&i.EncryptedAccessKey,
		&i.EncryptedSecretKey,
		&i.UseSsl,
		&i.Status,
		&i.Logo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE id = $1 AND user_id = $2
`

type DeleteCredentialParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteCredential, arg.ID, arg.UserID)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, user_id, name, provider, region, endpoint, encrypted_access_key, encrypted_secret_key, use_ssl, status, logo, created_at, updated_at FROM credentials
WHERE id = $1 AND user_id = $2
`

type GetCredentialParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.ID, arg.UserID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.Endpoint,
		&i.EncryptedAccessKey,
		&i.EncryptedSecretKey,
		&i.UseSsl,
		&i.Status,
		&i.Logo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, user_id, name, provider, region, endpoint, encrypted_access_key, encrypted_secret_key, use_ssl, status, logo, created_at, updated_at FROM credentials
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCredentials(ctx context.Context, userID pgtype.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Provider,
			&i.Region,
			&i.Endpoint,
			&i.EncryptedAccessKey,
			&i.EncryptedSecretKey,
			&i.UseSsl,
			&i.Status,
			&i.Logo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE credentials
SET name = $3, provider = $4, region = $5, endpoint = $6,
    encrypted_access_key = $7, encrypted_secret_key = $8,
    use_ssl = $9, status = $10, logo = $11, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdateCredentialParams struct {
	ID                 pgtype.UUID `json:"id"`
	UserID             pgtype.UUID `json:"user_id"`
	Name               string      `json:"name"`
	Provider           string      `json:"provider"`
	Region             string      `json:"region"`
	Endpoint           string      `json:"endpoint"`
	EncryptedAccessKey string      `json:"encrypted_access_key"`
	EncryptedSecretKey string      `json:"encrypted_secret_key"`
	UseSsl             bool        `json:"use_ssl"`
	Status             string      `json:"status"`
	Logo               *string     `json:"logo"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Provider,
		arg.Region,
		arg.Endpoint,
		arg.EncryptedAccessKey,
		arg.EncryptedSecretKey,
		arg.UseSsl,
		arg.Status,
		arg.Logo,
	)
	return err
}
