// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteBucket(ctx context.Context, arg DeleteBucketParams) error
	DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error
	DeleteSessionByHash(ctx context.Context, refreshTokenHash string) error
	DeleteSessionsForUser(ctx context.Context, userID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetBucket(ctx context.Context, arg GetBucketParams) (GetBucketRow, error)
	GetBucketByName(ctx context.Context, arg GetBucketByNameParams) (GetBucketByNameRow, error)
	GetCredential(ctx context.Context, arg GetCredentialParams) (Credential, error)
	GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error)
	GetProfileByUserID(ctx context.Context, userID pgtype.UUID) (Profile, error)
	GetSessionByHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertBucket(ctx context.Context, arg InsertBucketParams) (Bucket, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	ListBuckets(ctx context.Context, userID pgtype.UUID) ([]ListBucketsRow, error)
	ListCredentials(ctx context.Context, userID pgtype.UUID) ([]Credential, error)
	UpdateBucket(ctx context.Context, arg UpdateBucketParams) error
	UpdateBucketSize(ctx context.Context, arg UpdateBucketSizeParams) error
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error
	UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertProfile(ctx context.Context, arg UpsertProfileParams) error
}

var _ Querier = (*Queries)(nil)
